---
name: image
on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
          tags: |
            ${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:latest
